### ISSUE TITLE
Exception thrown when running against a Theme project

### ISSUE THREAD

**Issue by jagbarcelo** [lukaskabrt/PoExtractor#22]
When I run it against myTheme project (a theme project based on TheAgency theme) it throws this exception:

```
extractpo-oc G:\Documentos\GitLab\mySolution\myTheme G:\Documentos\TEMP --liquid
extractpo-oc : Unhandled exception. System.MissingMethodException: Method not found: 'System.Threading.Tasks.Task`1<Fluid.Values.FluidValue> Fluid.Ast.Expression.EvaluateAsync(Fluid.TemplateContext)'.
En línea: 1 Carácter: 1
+ extractpo-oc G:\Documentos\GitLab\mySolution\myTheme G:\Docume ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (Unhandled excep...plateContext)'.:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
   at PoExtractor.Liquid.LiquidStringExtractor.TryExtract(LiquidExpressionContext expressionContext, LocalizableStringOccurence& result)
   at PoExtractor.Liquid.ExtractingLiquidWalker.ProcessFilterExpression(FilterExpression filter) in D:\a\1\s\PoExtractor.Liquid\ExtractingLiquidWalker.cs:line 110
   at PoExtractor.Liquid.ExtractingLiquidWalker.Visit(Expression expression) in D:\a\1\s\PoExtractor.Liquid\ExtractingLiquidWalker.cs:line 96
   at PoExtractor.Liquid.ExtractingLiquidWalker.Visit(Statement node)
   at PoExtractor.Liquid.ExtractingLiquidWalker.Visit(Statement node) in D:\a\1\s\PoExtractor.Liquid\ExtractingLiquidWalker.cs:line 69
   at PoExtractor.Liquid.LiquidProjectProcessor.Process(String path, String basePath, LocalizableStringCollection strings) in D:\a\1\s\PoExtractor.Liquid\LiquidProjectProcessor.cs:line 38
   at PoExtractor.OrchardCore.Program.Main(String[] args) in D:\a\1\s\PoExtractor.OrchardCore\Program.cs:line 52
```

**Comment by lukaskabrt** [comment]
What version of OrchardCore and PoExtractor,OrchardCore do you use?

**Comment by jagbarcelo** [comment]
PoExtractor.OrchardCore is version 0.2.0
OrchardCore is RC 1

**Comment by lukaskabrt** [comment]
I think reason, why you see an error, is because the release of OrchardCore RC1 isn't aligned with the release of the latest PoExtractor. Can you please try this version? [PoExtractor.OrchardCore.zip](https://github.com/lukaskabrt/PoExtractor/files/3980646/PoExtractor.OrchardCore.zip)

**Comment by jagbarcelo** [comment]
Thanks @lukaskabrt 
It works fine:
>myTheme: Found 4 strings.

I had to manually uncompressed the zip file into the directory:
>C:\Users\MYUSERNAME\\.dotnet\tools\.store\poextractor.orchardcore\0.2.0\poextractor.orchardcore\0.2.0\tools\netcoreapp3.0\any

where there seemed to be an equivalent set of files (from the version installed via `dotnet tool install --global PoExtractor.OrchardCore`). I suppose that the way for this 'patch'.

**Comment by lukaskabrt** [comment]
Great. Thanks for the test. I will be more careful to align version of PoExtractor with the version of OrchardCore next time. Version working with OrchardCore is published on NuGet.org as `https://www.nuget.org/packages/PoExtractor.OrchardCore/0.2.0-rc1`
